version: '3.7'

services:
  db:
    build:
      context: ../
      dockerfile: ./deployments/db/Dockerfile
    container_name: syn_mongodb
    networks:
      - syn_net
    volumes:
      - syn_mongodb_volume:/data/db
    ports:
      - "30017:27017"
    env_file:
      - db/.env.dev.db

networks:
  syn_net:
    name: syn_mongodb

volumes:
  syn_python_volume:
    name: syn_python
  syn_mongodb_volume:
    name: syn_mongodb
